#version: "3.9"
#services:
#    servEstoque:
#        ports: 
#            - "8081:8080"
#        image: "estoque:latest"
#    servVendas:
#        ports: 
#            - "8082:8080"
#        image: "vendas:latest"
#    gateway:
#        ports:
#            - "8080:8080"
#        image: "gateway:latest"


version: "2"
services:
#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
  servVendas:
#    depends_on:
#      - "rabbitmq"
    ports:
      - "8081:8080"
    build: ./registraVendas
    image: "vendas:latest"
  servEstoque:
#    depends_on:
#      - "rabbitmq"
    ports:
      - "8082:8080"
    build: ./estoque
    image: "estoque:latest"
  gateway:
    ports:
      - "8080:8080"
    depends_on:
      - "servVendas"
      - "servEstoque"
    build: ./gateway
    image: "gateway:latest"